"""full_schema

Revision ID: 5d8e9dac9fa6
Revises: 
Create Date: 2026-04-27 14:35:42.282307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5d8e9dac9fa6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('revoked_refresh_jtis',
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('jti')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('caregiver_patient_links',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('caregiver_user_id', sa.Uuid(), nullable=False),
    sa.Column('patient_user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['caregiver_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('caregiver_user_id', 'patient_user_id', name='uq_caregiver_patient')
    )
    op.create_index(op.f('ix_caregiver_patient_links_caregiver_user_id'), 'caregiver_patient_links', ['caregiver_user_id'], unique=False)
    op.create_index(op.f('ix_caregiver_patient_links_patient_user_id'), 'caregiver_patient_links', ['patient_user_id'], unique=False)
    op.create_table('medications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('patient_user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('dosage', sa.String(length=200), nullable=False),
    sa.Column('reminder_mode', sa.String(length=32), nullable=False),
    sa.Column('interval_minutes', sa.Integer(), nullable=True),
    sa.Column('slot_times', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['patient_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medications_patient_user_id'), 'medications', ['patient_user_id'], unique=False)
    op.create_table('patient_profiles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('first_name', sa.String(length=200), nullable=False),
    sa.Column('middle_name', sa.String(length=200), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('link_token', sa.String(length=64), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_patient_profiles_link_token'), 'patient_profiles', ['link_token'], unique=True)
    op.create_table('intake_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('patient_user_id', sa.Uuid(), nullable=False),
    sa.Column('medication_id', sa.Uuid(), nullable=True),
    sa.Column('medication_name_snapshot', sa.String(length=500), nullable=False),
    sa.Column('dosage_snapshot', sa.String(length=200), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('snooze_until', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['medication_id'], ['medications.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intake_events_medication_id'), 'intake_events', ['medication_id'], unique=False)
    op.create_index(op.f('ix_intake_events_patient_user_id'), 'intake_events', ['patient_user_id'], unique=False)
    op.create_table('missed_intake_alerts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('patient_user_id', sa.Uuid(), nullable=False),
    sa.Column('medication_id', sa.Uuid(), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notified_caregiver_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['medication_id'], ['medications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_user_id', 'medication_id', 'due_at', name='uq_missed_patient_med_due')
    )
    op.create_index(op.f('ix_missed_intake_alerts_medication_id'), 'missed_intake_alerts', ['medication_id'], unique=False)
    op.create_index(op.f('ix_missed_intake_alerts_patient_user_id'), 'missed_intake_alerts', ['patient_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_missed_intake_alerts_patient_user_id'), table_name='missed_intake_alerts')
    op.drop_index(op.f('ix_missed_intake_alerts_medication_id'), table_name='missed_intake_alerts')
    op.drop_table('missed_intake_alerts')
    op.drop_index(op.f('ix_intake_events_patient_user_id'), table_name='intake_events')
    op.drop_index(op.f('ix_intake_events_medication_id'), table_name='intake_events')
    op.drop_table('intake_events')
    op.drop_index(op.f('ix_patient_profiles_link_token'), table_name='patient_profiles')
    op.drop_table('patient_profiles')
    op.drop_index(op.f('ix_medications_patient_user_id'), table_name='medications')
    op.drop_table('medications')
    op.drop_index(op.f('ix_caregiver_patient_links_patient_user_id'), table_name='caregiver_patient_links')
    op.drop_index(op.f('ix_caregiver_patient_links_caregiver_user_id'), table_name='caregiver_patient_links')
    op.drop_table('caregiver_patient_links')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('revoked_refresh_jtis')
    # ### end Alembic commands ###
